ci(publish): upload rock using luarocks cli

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -11,40 +11,43 @@ jobs:
       contents: write
     env:
       package_name: lls-addon-penlight
-      spec_revision: 1
-      src_rock_name: ""
+      spec_version: "" # this gets set in the Get Rockspec Version step
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Publish to LuaRocks
-        uses: nvim-neorocks/luarocks-tag-release@v7
-        env:
-          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
-        with:
-          name: ${{ env.package_name }}
-          dependencies: |
-            lls-addon-luafilesystem
-          copy_directories: ""
-          license: MIT
-          template: ./.github/templates/rockspec.template
-          specrev: ${{ env.spec_revision }}
-
-      - name: Retrieve Source Rock
+      - name: Get Rockspec Version
         run: |
           if [[ "${{ github.ref_name }}" =~ ^v(.+)$ ]]; then
-            spec_version="${BASH_REMATCH[1]}-${{ env.spec_revision }}"
+            echo "spec_version=${BASH_REMATCH[1]}-1" >> $GITHUB_ENV
           else
-            echo "rockspec version not found" >&2
+            echo "rockspec version could not be matched" >&2
             exit 1
           fi
 
-          src_rock_name="${{ env.package_name }}-${spec_version}.src.rock"
-          curl --fail --output "${src_rock_name}" "https://luarocks.org/${src_rock_name}"
-          echo "src_rock_name=${src_rock_name}" >> $GITHUB_ENV
+      - uses: actions/checkout@v4
 
-      - name: GitHub Release
+      - name: Set up Lua
+        uses: leafo/gh-actions-lua@v11
+        with:
+          luaVersion: "5.4.8"
+
+      - name: Set up LuaRocks
+        uses: leafo/gh-actions-luarocks@v5
+        with:
+          luaRocksVersion: "3.12.2"
+
+      - name: Write LuaRocks Rockspec
+        run: |
+          luarocks new_version \
+            --tag ${{ github.ref_name }}
+            ${{ env.package_name }}-release-1.rockspec
+
+      - name: Publish to LuaRocks
+        run: |
+          luarocks upload \
+            "./${{ env.package_name }}-${{ env.spec_version }}.rockspec" \
+            --api-key=${{ secrets.LUAROCKS_API_KEY }}
+
+      - name: Create GitHub Release
         uses: softprops/action-gh-release@v2
         with:
-          files: ${{ env.src_rock_name }}
+          files: "${{ env.package_name }}-${{ env.spec_version }}.src.rock"
